#
# Skipping commits affecting these files.
#
skip_commits:
   files:
    - '**/*.md'

environment:
  matrix:
    - BUILDER: visualc
      CPU:     x86
    - BUILDER: visualc
      CPU:     x64
    - BUILDER: clang
      CPU:     x86
    - BUILDER: clang
      CPU:     x64
    - BUILDER: mingw64
      CPU:     x86
    - BUILDER: mingw64
      CPU:     x64
    - BUILDER: borland
      CPU:     x86
    - BUILDER: djgpp
      CPU:     x86
    - BUILDER: watcom
      CPU:     x86
      MODEL:   win32
    - BUILDER: watcom
      CPU:     x86
      MODEL:   flat
    - BUILDER: watcom
      CPU:     x86
      MODEL:   large

matrix:
  #
  # Immediately finish build if one of the above jobs fails.
  #
  fast_finish: true
  allow_failures:
     - BUILDER: mingw64
     - BUILDER: clang

install:
  #
  # Prepend the PATH for 'make' + 'sh' used by 'MinGW', 'djgpp', 'CygWin' etc.
  #
  - cmd: set PATH=c:\msys64\usr\bin;%PATH%

  #
  # Set compiler environment for MSVC/clang-cl first.
  # (the env-vars for 'BUILDER=watcom' is done in 'appveyor-script.bat').
  #
  - cmd: if %BUILDER%. == visualc.           call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%
  - cmd: if %BUILDER%. == clang.             call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%
  - cmd: if %BUILDER%-%CPU%. == mingw64-x86. set PATH=c:\msys64\MinGW32\bin;%PATH%
  - cmd: if %BUILDER%-%CPU%. == mingw64-x64. set PATH=c:\msys64\MinGW64\bin;%PATH%

build_script:
    - cmd: appveyor-script.bat build_src
    - cmd: appveyor-script.bat build_bin

test_script:
#    - cmd: set PATH=c:\Python34;%PATH% & python.exe appveyor-script.py build_tests
     - cmd: appveyor-script.bat build_tests

#
# Try to preserve previously downloaded CI packages, the 'src/build'
# and 'lib' files.
#
cache:
  - '%APPVEYOR_BUILD_FOLDER%\CI-temp'
  - 'c:\Program Files (x86)\LLVM'

